// object containing all routes and their required imports to manage
// helps standardize across app entrypoints whether HAXcms, HAXsite or CLI based
const RoutesMap = {
  post: {
    login: require('../routes/login.js'),
    logout: require('../routes/logout.js'),
    formLoad: require('../routes/formLoad.js'),
    formProcess: require('../routes/formProcess.js'),
    getUserData: require('../routes/getUserData.js'),
    listSites: require('../routes/listSites.js'),

    siteUpdateAlternateFormats: require('../routes/siteUpdateAlternateFormats.js'),
    createSite: require('../routes/createSite.js'),
    cloneSite: require('../routes/cloneSite.js'),
    archiveSite: require('../routes/archiveSite.js'),
    downloadSite: require('../routes/downloadSite.js'),
    downloadSiteSkeleton: require('../routes/downloadSiteSkeleton.js'),
    saveSiteAsTemplate: require('../routes/saveSiteAsTemplate.js'),
    saveManifest: require('../routes/saveManifest.js'),
    saveAppearanceSettings: require('../routes/saveAppearanceSettings.js'),
    savePlatformSettings: require('../routes/savePlatformSettings.js'),
    saveAllowedBlocks: require('../routes/saveAllowedBlocks.js'),
    saveEditorSettings: require('../routes/saveEditorSettings.js'),
    saveSeoSettings: require('../routes/saveSeoSettings.js'),
    saveOutline: require('../routes/saveOutline.js'),

    createNode: require('../routes/createNode.js'),
    saveNode: require('../routes/saveNode.js'),
    saveNodeDetails: require('../routes/saveNodeDetails.js'),
    getNodeRevisions: require('../routes/getNodeRevisions.js'),
    getNodeRevision: require('../routes/getNodeRevision.js'),
    restoreNodeRevision: require('../routes/restoreNodeRevision.js'),
    deleteNode: require('../routes/deleteNode.js'),
    siteSearch: require('../routes/siteSearch.js'),
    insights: require('../routes/insights.js'),
    linkChecker: require('../routes/linkChecker.js'),
    contentBrowser: require('../routes/contentBrowser.js'),
    mediaBrowser: require('../routes/mediaBrowser.js'),
    listFiles: require('../routes/listFiles.js'),
    saveFile: require('../routes/saveFile.js'),
    fileOperation: require('../routes/fileOperation.js'),
    // allow AppHax API (which defaults to POST) to call connectionSettings,
    // refreshAccessToken, and skeletonsList while still supporting GET
    // for other clients; systemStatus is intentionally POST-only
    connectionSettings: require('../routes/connectionSettings.js'),
    connectionTest: require('../routes/connectionTest.js'),
    appStoreSearch: require('../routes/appStoreSearch.js'),
    refreshAccessToken: require('../routes/refreshAccessToken.js'),
    systemStatus: require('../routes/systemStatus.js'),
    getApiKeys: require('../routes/getApiKeys.js'),
    saveApiKeys: require('../routes/saveApiKeys.js'),
    getMediaSettings: require('../routes/getMediaSettings.js'),
    saveMediaSettings: require('../routes/saveMediaSettings.js'),
    saveEnabledSkeletons: require('../routes/saveEnabledSkeletons.js'),
    schemaFileOperation: require('../routes/schemaFileOperation.js'),
    saveEnabledThemes: require('../routes/saveEnabledThemes.js'),
    saveEnabledBlocks: require('../routes/saveEnabledBlocks.js'),
    systemBlocksList: require('../routes/systemBlocksList.js'),
    skeletonsList: require('../routes/skeletonsList.js'),
    themesList: require('../routes/themesList.js'),
    getSkeleton: require('../routes/getSkeleton.js'),
    // meta endpoints mirroring PHP Operations::options and ::api
    options: require('../routes/options.js'),
    api: require('../routes/api.js'),
  },
  get: {
    logout: require('../routes/logout.js'),
    listFiles: require('../routes/listFiles.js'),
    openapi: require('../routes/openapi.js'),
    "openapi/json": require('../routes/openapi.js'),
    connectionSettings: require('../routes/connectionSettings.js'),
    connectionTest: require('../routes/connectionTest.js'),
    appStoreSearch: require('../routes/appStoreSearch.js'),
    generateAppStore: require('../routes/generateAppStore.js'),
    systemBlocksList: require('../routes/systemBlocksList.js'),
    refreshAccessToken: require('../routes/refreshAccessToken.js'),
    skeletonsList: require('../routes/skeletonsList.js'),
    themesList: require('../routes/themesList.js'),
    getSkeleton: require('../routes/getSkeleton.js'),
  },
};

// these routes need to return a response without a JWT validation
const OpenRoutes = [
  'generateAppStore',
  'connectionSettings',
  'connectionTest',
  'getSitesList',
  'getSkeleton',
  'login',
  'logout',
  'api',
  'options',
  'openapi',
  'openapi/json',
  'refreshAccessToken'
];
// haxcms system-admin routes should only be available from system dashboard context
// future system-admin endpoints should be added here
const SystemAdminRoutes = [
  'listSites',
  'createSite',
  'cloneSite',
  'archiveSite',
  'downloadSite',
  'downloadSiteSkeleton',
  'saveSiteAsTemplate',
  'systemStatus',
  'getApiKeys',
  'saveApiKeys',
  'getMediaSettings',
  'saveMediaSettings',
  'saveEnabledBlocks',
  'systemBlocksList',
  'saveEnabledThemes',
  'saveEnabledSkeletons',
  'schemaFileOperation',
  'skeletonsList',
  'themesList',
  'getSkeleton',
];

module.exports = {RoutesMap, OpenRoutes, SystemAdminRoutes};
