openapi: 3.0.0
info:
  title: HAXcms API
  description: Legacy HAXcms API routes that are not yet ported to v1
  termsOfService: https://haxtheweb.org
  contact:
    email: hax@psu.edu
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: null
servers: null
paths:
  /siteUpdateAlternateFormats:
    post:
      tags:
        - cms
        - authenticated
        - meta
      operationId: Operations::siteUpdateAlternateFormats
      requestBody:
        content:
          application/json:
            schema:
              required:
                - site
              properties:
                site:
                  type: object
                format:
                  type: string
              type: object
      responses:
        "200":
          description: Update the alternative formats surrounding a site
  /formLoad:
    post:
      tags:
        - cms
        - authenticated
        - form
      operationId: Operations::formLoad
      requestBody:
        content:
          application/json:
            schema:
              required:
                - token
                - haxcms_form_id
              properties:
                token:
                  type: string
                haxcms_form_id:
                  type: string
                site:
                  type: object
                node:
                  type: object
              type: object
      responses:
        "200":
          description: Load a form based on ID
  /formProcess:
    post:
      tags:
        - cms
        - authenticated
        - form
      operationId: Operations::formProcess
      requestBody:
        content:
          application/json:
            schema:
              required:
                - haxcms_form_id
                - haxcms_form_token
              properties:
                haxcms_form_id:
                  type: string
                haxcms_form_token:
                  type: string
                site:
                  type: object
                node:
                  type: object
              type: object
      responses:
        "200":
          description: Process a form based on ID and input data
tags:
  - name: hax
    description: Operations required for HAX editor to work
    externalDocs:
      description: Find out more about hax editor integrations
      url: https://haxtheweb.org/integrations/create-new-ones
  - name: cms
    description: Operations for the CMS side
  - name: site
    description: Operations for sites
  - name: node
    description: Operations for individual nodes in a site
  - name: file
    description: Operations for files related to CMS or HAX
  - name: form
    description: Operations related to form submission or generation
  - name: meta
    description: Operations related to metadata management or processes
  - name: git
    description: Operations related to git / version control of the site
  - name: user
    description: Operations for the user account / object
  - name: api
    description: endpoint to generate the API or surrounding API callbacks
  - name: settings
    description: Internal settings related to configuration of this HAXcms deployment
  - name: authenticated
    description: Operations requiring authentication
externalDocs:
  description: HAXcms and all things HAX documentations
  url: https://haxtheweb.org/
